"""Add Admin model

Revision ID: 730cf42e3d0e
Revises: 55931c74942f
Create Date: 2025-06-23 15:29:28.279539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '730cf42e3d0e'
down_revision = '55931c74942f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admins')
    # ### end Alembic commands ###
